[package]
name = "encryption-simple-rs"
version = "0.1.0"
edition = '2021'
license = "GPL-2.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
mariadb = { path = "../../mariadb" }
sha2 = "0.10"
rand = "0.8"
