[package]
name = "mariadb-sys"
version = "0.1.0"
edition = '2021'
license = "GPL-2.0-only"


[build-dependencies]
autocxx-build = "0.26.0"
bindgen = "0.68.1"
cmake = "0.1.50"
doxygen-rs = "0.4.2"

[dependencies]
autocxx = "0.26.0"
