[package]
name = "storage-csv"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
mariadb = { path = "../../mariadb", features = ["storage"] }
